# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/jide/sk1wg/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES := \
    vendor/jide/sk1wg/proprietary/bin/add_p2p_iface.sh:system/bin/add_p2p_iface.sh \
    vendor/jide/sk1wg/proprietary/bin/cluster_get.sh:system/bin/cluster_get.sh \
    vendor/jide/sk1wg/proprietary/bin/cluster_set.sh:system/bin/cluster_set.sh \
    vendor/jide/sk1wg/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/jide/sk1wg/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/jide/sk1wg/proprietary/bin/mount_debugfs.sh:system/bin/mount_debugfs.sh \
    vendor/jide/sk1wg/proprietary/bin/nvcpuvoltcapd:system/bin/nvcpuvoltcapd \
    vendor/jide/sk1wg/proprietary/bin/screencap:system/bin/screencap \
    vendor/jide/sk1wg/proprietary/bin/screenrecord:system/bin/screenrecord \
    vendor/jide/sk1wg/proprietary/bin/set_hwui_params.sh:system/bin/set_hwui_params.sh \
    vendor/jide/sk1wg/proprietary/bin/tinycap:system/bin/tinycap \
    vendor/jide/sk1wg/proprietary/bin/tinymix:system/bin/tinymix \
    vendor/jide/sk1wg/proprietary/bin/tinyplay:system/bin/tinyplay \
    vendor/jide/sk1wg/proprietary/bin/ussr_setup.sh:system/bin/ussr_setup.sh \
    vendor/jide/sk1wg/proprietary/bin/xaplay:system/bin/xaplay \
    vendor/jide/sk1wg/proprietary/etc/firmware/nvavp_aud_ucode.bin:system/etc/firmware/nvavp_aud_ucode.bin \
    vendor/jide/sk1wg/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
    vendor/jide/sk1wg/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
    vendor/jide/sk1wg/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
    vendor/jide/sk1wg/proprietary/etc/firmware/tegra11x/nvhost_msenc02.fw:system/etc/firmware/tegra11x/nvhost_msenc02.fw \
    vendor/jide/sk1wg/proprietary/etc/firmware/tegra11x/nvhost_tsec.fw:system/etc/firmware/tegra11x/nvhost_tsec.fw \
    vendor/jide/sk1wg/proprietary/etc/hdcpsrm/hdcp1x.srm:system/etc/hdcpsrm/hdcp1x.srm \
    vendor/jide/sk1wg/proprietary/etc/hdcpsrm/hdcp2x.srm:system/etc/hdcpsrm/hdcp2x.srm \
    vendor/jide/sk1wg/proprietary/etc/hdcpsrm/hdcp2xtest.srm:system/etc/hdcpsrm/hdcp2xtest.srm \
    vendor/jide/sk1wg/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/jide/sk1wg/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/jide/sk1wg/proprietary/lib/libnvoice.so:system/lib/libnvoice.so \
    vendor/jide/sk1wg/proprietary/lib/libopencv24_tegra.so:system/lib/libopencv24_tegra.so \
    vendor/jide/sk1wg/proprietary/lib/libpower.so:system/lib/libpower.so \
    vendor/jide/sk1wg/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/jide/sk1wg/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/jide/sk1wg/proprietary/lib/librm31080.so:system/lib/librm31080.so \
    vendor/jide/sk1wg/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_http_support.so:system/lib/libstagefright_http_support.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_httplive.so:system/lib/libstagefright_httplive.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_aacdec.so:system/lib/libstagefright_soft_aacdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_aacenc.so:system/lib/libstagefright_soft_aacenc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_amrdec.so:system/lib/libstagefright_soft_amrdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_amrnbenc.so:system/lib/libstagefright_soft_amrnbenc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_amrwbenc.so:system/lib/libstagefright_soft_amrwbenc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_flacenc.so:system/lib/libstagefright_soft_flacenc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_g711dec.so:system/lib/libstagefright_soft_g711dec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_gsmdec.so:system/lib/libstagefright_soft_gsmdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_h264dec.so:system/lib/libstagefright_soft_h264dec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_h264enc.so:system/lib/libstagefright_soft_h264enc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_hevcdec.so:system/lib/libstagefright_soft_hevcdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_mp3dec.so:system/lib/libstagefright_soft_mp3dec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_mpeg4enc.so:system/lib/libstagefright_soft_mpeg4enc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_opusdec.so:system/lib/libstagefright_soft_opusdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_rawdec.so:system/lib/libstagefright_soft_rawdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_vorbisdec.so:system/lib/libstagefright_soft_vorbisdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_vpxdec.so:system/lib/libstagefright_soft_vpxdec.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_soft_vpxenc.so:system/lib/libstagefright_soft_vpxenc.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_wfd.so:system/lib/libstagefright_wfd.so \
    vendor/jide/sk1wg/proprietary/lib/libstagefright_yuv.so:system/lib/libstagefright_yuv.so \
    vendor/jide/sk1wg/proprietary/lib/libtbb.so:system/lib/libtbb.so \
    vendor/jide/sk1wg/proprietary/lib/libtf_crypto_sst.so:system/lib/libtf_crypto_sst.so \
    vendor/jide/sk1wg/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/jide/sk1wg/proprietary/lib/egl/libEGL_tegra_impl.so:system/lib/egl/libEGL_tegra_impl.so \
    vendor/jide/sk1wg/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/jide/sk1wg/proprietary/lib/egl/libGLESv1_CM_tegra_impl.so:system/lib/egl/libGLESv1_CM_tegra_impl.so \
    vendor/jide/sk1wg/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/jide/sk1wg/proprietary/lib/egl/libGLESv2_tegra_impl.so:system/lib/egl/libGLESv2_tegra_impl.so \
    vendor/jide/sk1wg/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/jide/sk1wg/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/jide/sk1wg/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/jide/sk1wg/proprietary/lib/hw/keystore.tegra.so:system/lib/hw/keystore.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/lights.macallan.so:system/lib/hw/lights.macallan.so \
    vendor/jide/sk1wg/proprietary/lib/hw/nfc.tegra.so:system/lib/hw/nfc.tegra.so \
    vendor/jide/sk1wg/proprietary/lib/hw/sensors.macallan.so:system/lib/hw/sensors.macallan.so \
    vendor/jide/sk1wg/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/jide/sk1wg/proprietary/lib/hw/ts.default.so:system/lib/hw/ts.default.so \
    vendor/jide/sk1wg/proprietary/lib/nvcms/device.cfg:system/lib/nvcms/device.cfg \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/jide/sk1wg/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
    vendor/jide/sk1wg/proprietary/vendor/bin/nv_hciattach:system/vendor/bin/nv_hciattach \
    vendor/jide/sk1wg/proprietary/vendor/bin/nvcgcserver:system/vendor/bin/nvcgcserver \
    vendor/jide/sk1wg/proprietary/vendor/bin/tegrastats:system/vendor/bin/tegrastats \
    vendor/jide/sk1wg/proprietary/vendor/bin/usdwatchdog:system/vendor/bin/usdwatchdog \
    vendor/jide/sk1wg/proprietary/vendor/bin/ussrd:system/vendor/bin/ussrd \
    vendor/jide/sk1wg/proprietary/vendor/lib/libussrd.so:system/vendor/lib/libussrd.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/hw/power.macallan.so:system/vendor/lib/hw/power.macallan.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libardrv_dynamic.so:system/vendor/lib/libardrv_dynamic.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvapputil.so:system/vendor/lib/libnvapputil.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvaudioservice.so:system/vendor/lib/libnvaudioservice.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libaudioavp.so:system/vendor/lib/libaudioavp.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libcgdrv.so:system/vendor/lib/libcgdrv.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libcplconnectclient.so:system/vendor/lib/libcplconnectclient.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libfcamdng.so:system/vendor/lib/libfcamdng.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libgov_combinator.so:system/vendor/lib/libgov_combinator.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libgov_cores.so:system/vendor/lib/libgov_cores.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libgov_cpufs.so:system/vendor/lib/libgov_cpufs.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libgov_gpufs.so:system/vendor/lib/libgov_gpufs.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libgov_tbc.so:system/vendor/lib/libgov_tbc.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvavp.so:system/vendor/lib/libnvavp.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvcamerahdr.so:system/vendor/lib/libnvcamerahdr.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvcam_imageencoder.so:system/vendor/lib/libnvcam_imageencoder.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvcontrol_jni.so:system/vendor/lib/libnvcontrol_jni.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvcpl.so:system/vendor/lib/libnvcpl.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvddk_2d.so:system/vendor/lib/libnvddk_2d.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvddk_2d_v2.so:system/vendor/lib/libnvddk_2d_v2.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvfusebypass.so:system/vendor/lib/libnvfusebypass.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvglsi.so:system/vendor/lib/libnvglsi.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_audio.so:system/vendor/lib/libnvmm_audio.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_camera.so:system/vendor/lib/libnvmm_camera.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_contentpipe.so:system/vendor/lib/libnvmm_contentpipe.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_image.so:system/vendor/lib/libnvmm_image.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmmlite_audio.so:system/vendor/lib/libnvmmlite_audio.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmmlite_image.so:system/vendor/lib/libnvmmlite_image.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmmlite.so:system/vendor/lib/libnvmmlite.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmmlite_utils.so:system/vendor/lib/libnvmmlite_utils.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmmlite_video.so:system/vendor/lib/libnvmmlite_video.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_manager.so:system/vendor/lib/libnvmm_manager.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_parser.so:system/vendor/lib/libnvmm_parser.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_service.so:system/vendor/lib/libnvmm_service.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm.so:system/vendor/lib/libnvmm.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_utils.so:system/vendor/lib/libnvmm_utils.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_video.so:system/vendor/lib/libnvmm_video.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvmm_writer.so:system/vendor/lib/libnvmm_writer.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvodm_dtvtuner.so:system/vendor/lib/libnvodm_dtvtuner.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvodm_hdmi.so:system/vendor/lib/libnvodm_hdmi.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvodm_imager.so:system/vendor/lib/libnvodm_imager.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvodm_misc.so:system/vendor/lib/libnvodm_misc.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvodm_query.so:system/vendor/lib/libnvodm_query.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvomxadaptor.so:system/vendor/lib/libnvomxadaptor.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvomxilclient.so:system/vendor/lib/libnvomxilclient.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvomx.so:system/vendor/lib/libnvomx.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvos.so:system/vendor/lib/libnvos.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvparser.so:system/vendor/lib/libnvparser.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvrm_graphics.so:system/vendor/lib/libnvrm_graphics.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvrm.so:system/vendor/lib/libnvrm.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvsm.so:system/vendor/lib/libnvsm.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvstitching.so:system/vendor/lib/libnvstitching.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvtestio.so:system/vendor/lib/libnvtestio.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvtestresults.so:system/vendor/lib/libnvtestresults.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvtnr.so:system/vendor/lib/libnvtnr.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvtvmr.so:system/vendor/lib/libnvtvmr.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvwinsys.so:system/vendor/lib/libnvwinsys.so \
    vendor/jide/sk1wg/proprietary/vendor/lib/libnvwsi.so:system/vendor/lib/libnvwsi.so
